### ISSUE TITLE
NPE when get files from commit

### ISSUE THREAD

**Issue by ts-huyao** [jenkinsci/pipeline-github-plugin#24]
Hi,
I need to get modified files from current commit to decide if current stage worth proceeding.
```
def nonK8sChanged() {
    if (pullRequest.commits) {
        for (commit in pullRequest.commits) {
            if (commit.sha == env.GIT_COMMIT) {
                for (commitFile in commit.files) {  <- NPE here
                    echo "SHA: ${commitFile.sha} File Name: ${commitFile.filename} Status: ${commitFile.status}"
                    if (!(commitFile.filename ==~ /\w\s+kubernetes\\/.+/)) {
                        return true
                    }
                }
            }
        }
    }
    return false
}
```
Throws following exception
```
java.lang.NullPointerException
	at org.jenkinsci.plugins.pipeline.github.CommitGroovyObject.getFiles(CommitGroovyObject.java:120)
	at org.jenkinsci.plugins.pipeline.github.CommitGroovyObject.getProperty(CommitGroovyObject.java:83)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:174)
```
I tried echo $(git diff-tree --no-commit-id --name-status -r HEAD) it looks ok.
Thank you for the help.

**Comment by aaronjwhiteside** [comment]
I've tried reproducing this with your exact example, and I don't get the NPE.

**Comment by ts-huyao** [comment]
commit.dump() is as following
```
<org.jenkinsci.plugins.pipeline.github.CommitGroovyObject@1a9562b1 commit=org.eclipse.egit.github.core.RepositoryCommit@51e2cb4e commitService=org.jenkinsci.plugins.pipeline.github.client.ExtendedCommitService@60d3ab29 base=TradeshiftCN/cn-pay-coresetup>
```
I believe the issue is [here](https://github.com/jenkinsci/pipeline-github-plugin/blob/a85845d0246aeb3c6d33620db59988a75cc927d6/src/main/java/org/jenkinsci/plugins/pipeline/github/CommitGroovyObject.java#L135)
```
commit.getFiles() is null , steam() throws NPE
```
I'm working on a organization repo, I'm not sure if this is related. and strangely 
```
pullRequest.files
```
works

stack trace is 
```
java.lang.NullPointerException
	at org.jenkinsci.plugins.pipeline.github.CommitGroovyObject.getFiles(CommitGroovyObject.java:120)
	at org.jenkinsci.plugins.pipeline.github.CommitGroovyObject.getProperty(CommitGroovyObject.java:83)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:174)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:456)
	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:290)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onGetProperty(GroovyInterceptor.java:68)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:326)
	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:288)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:292)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at WorkflowScript.nonK8sChanged(WorkflowScript:84)
	at WorkflowScript.run(WorkflowScript:31)
```

**Comment by aaronjwhiteside** [comment]
thanks @ts-huyao, although I couldn't reproduce the issue on my end, I've added protections against there being no file modifications in a commit.
