### ISSUE TITLE
Missing pullRequest global in build with env.CHANGE_ID present

### ISSUE THREAD

**Issue by macb** [jenkinsci/pipeline-github-plugin#33]
Given the below Jenkinsfile in a project created with the `Github Organization` plugin.
```groovy
pipeline {
  stages {
    stage('Pull changes') {
      steps {
        checkout scm
      }
    }
    stage('Generate diff') {
      when { changeRequest() }
      steps {
        script {
          echo "$env.CHANGE_ID"
          if (env.CHANGE_ID) {
              pullRequest.comment("hello world")
          }
        }
      }
    }
  }
}
```

The `echo` will output the expected pull request #, however the subsequent call to `pullRequest` will fail with:
`No such property: pullRequest for class: groovy.lang.Binding`

The UI also tracks it as a pull request and PR status is updated as expected. Build is manually scheduled.

Found a related stackoverflow but it's a workaround, not really a solution (https://stackoverflow.com/questions/50488566/add-a-comment-in-github-pull-request-in-jenkins)

**Comment by aaronjwhiteside** [comment]
@macb just wanting to check how you resolved this issue? 

I also just wanted to double check that you have the `Pipeline GitHub Plugin` version 2.1 installed, which is a separate plugin to the `GitHub Pull Request Builder` plugin which is mentioned in the StackOverflow article

My first impression based on what I see here, would be that you don't have this exact plugin installed.

Anyway let me know if there is anything I can help with :)

**Comment by aliasmani** [comment]
@macb  May I know How you solved this issue?. I am having Change_ID  set to NULL. The build is not seen as a PR trigger!!!

**Comment by walkingpendulum** [comment]
still have this issue!

pipeline:
```Jenkinsfile
pipeline {
    agent any
    triggers {
        githubPullRequests events: [commentPattern('run job please')], spec: '', triggerMode: 'HEAVY_HOOKS'
    }
    stages {
        stage("Do work") {
            steps {
                script {
                    pullRequest.comment("☁️🚀🌞 deploy & run integration started")
                }
                sh './main_script.sh'
            }
        }
    }

    post {
        success {
            script {
                pullRequest.comment("🌞 Job completed successfully")
            }
        }
        failure {
            script {
                pullRequest.comment("Job completed with errors 🤔")
            }
        }
    }
}
```

error:
```
Error when executing failure post condition:
groovy.lang.MissingPropertyException: No such property: pullRequest for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:264)
	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:288)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:292)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:268)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:268)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:268)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at WorkflowScript.run(WorkflowScript:57)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
	at sun.reflect.GeneratedMethodAccessor367.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$101(SandboxContinuable.java:34)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.lambda$run0$0(SandboxContinuable.java:59)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:121)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:58)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:182)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:332)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:83)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:244)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:232)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

Jenkins ver. 2.150.2
plugin version 2.3

**Comment by aaronjwhiteside** [comment]
@walkingpendulum I don't see anything in this example that restricts this pipeline to PRs only, you've just got a trigger..

Please have a read of the declarative pipeline syntax from https://jenkins.io/doc/book/pipeline/syntax/#when

In that document there is a when statement that should restrict the pipeline to pull requests only

```groovy
when { changeRequest() }
```

**Comment by walkingpendulum** [comment]
@aaronjwhiteside thank yoy for fast reply!
actually I restrict pipeline to PR only with webhooks (only isssue comments).
I just checked and 
```
if (env.CHANGE_ID) {
    pullRequest.comment("🌞 Job completed successfully")
}
```
does not work

**Comment by rcooo** [comment]
I am also experiencing same issue
```groovy
...
failure {
    script {
        if (env.CHANGE_ID) {
            echo 'Something failed, send PR comment.';
            def comment = pullRequest.comment('Hello, something failed!');
            // This doesn't work.
            // groovy.lang.MissingPropertyException: No such property: pullRequest for class: groovy.lang.Binding
        } else {
            echo 'Nope, its not a PR!';
        }
    }
}
...
```

Everything (environment, projects, plugins) seems to be configured fine. Searched everywhere on internet where can be the problem and nothing has worked so far 😟

**Comment by aaronjwhiteside** [comment]
```groovy
pipeline {
    agent any
    stages {
        stage('Test') {
            when { 
                changeRequest() 
            }
            steps {
                echo "Current Pull Request ID: ${pullRequest.id}"
            }
        }
    }
}
```

This works as expected for me.

```
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Test)
[Pipeline] echo
Current Pull Request ID: 116015340
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
```

**Comment by derryx** [comment]
Hi!

I have a similar problem. My build gets triggered fine by an opened PR. Neither CHANGE_ID nor the "pullRequest" object are there.

Following environment entries are there:
`
GIT_PREVIOUS_SUCCESSFUL_COMMIT=9364777d1ef887d66002abf5c6a34de0f62ac1ec
GITHUB_REPO_GIT_URL=git://github.com/...
GITHUB_PR_SOURCE_BRANCH=development
GIT_COMMIT=9364777d1ef887d66002abf5c6a34de0f62ac1ec
GITHUB_REPO_SSH_URL=git@github.com,....
GITHUB_PR_COND_REF=head
GIT_BRANCH=origin/development
GITHUB_PR_NUMBER=8
GITHUB_PR_STATE=OPEN
GITHUB_PR_SOURCE_REPO_OWNER=.....
GITHUB_PR_CAUSE_SKIP=false
GITHUB_PR_TITLE=Development
GITHUB_PR_TRIGGER_SENDER_AUTHOR=....
GITHUB_PR_SHORT_DESC=GitHub PR #.....
GITHUB_PR_HEAD_SHA=9364777d1ef887d66002abf5c6a34de0f62ac1ec
GITHUB_PR_TARGET_BRANCH=master
GIT_PREVIOUS_COMMIT=9364777d1ef887d66002abf5c6a34de0f62ac1ec
GITHUB_PR_URL=https://github.com.....
`

CU
Thomas

**Comment by rcooo** [comment]
@aaronjwhiteside Hey! Even if I use this simple script, it's not working...
```groovy
pipeline {
    agent any

    stages {
        stage('Test') {
            when {
                changeRequest()
            }
            steps {
                echo "Current Pull Request ID: ${pullRequest.id}"
            }
        }
    }
}
```
I am using latest versions of jenkins and all plugins required to be able to use this. Even tried both declarative and scripted pipelines. Neither one worked.

**Comment by aaronjwhiteside** [comment]
@rcooo can you show me a full stacktrace?

@derryx It looks like you are using the https://wiki.jenkins.io/display/JENKINS/GitHub+pull+request+builder+plugin and not the GitHub Branch Source plugin https://wiki.jenkins.io/display/JENKINS/GitHub+Branch+Source+Plugin, Pipeline GitHub Plugin requires GitHub jobs to be initiated by the GitHub Branch Source Plugin.

**Comment by staffanselander** [comment]
I think I have the same problem as the one above. I have the following pipeline.

```
pipeline {

  agent any

  stages {
    stage('Test') {
      when { changeRequest() }
      steps {
        script {
          echo "Current Pull Request ID: ${env.CHANGE_ID}"
        }
      }
    }
    stage('Test2') {
      steps {
        script {
          pullRequest.comment("Test")
        }
      }
    }
  }
}
```

The job executes and successfully prints "Current Pull Request ID: 1"
But then it fails on `stage('Test2')` with the following exception:

```
groovy.lang.MissingPropertyException: No such property: pullRequest for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:270)
	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:289)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:293)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:269)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:269)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:269)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at WorkflowScript.run(WorkflowScript:26)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:347)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:259)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:247)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Versions:
- Debian 9.7
- Jenkins 2.177
- GitHub Branch Source Plugin 2.5.2
- Job created by the GitHub Organization folder/project type.

**Comment by staffanselander** [comment]
Actually, I was fooled by the naming of the plugin name.
I didn't have the `https://plugins.jenkins.io/pipeline-github` plugin installed.

Works now!

**Comment by nishaprayaga** [comment]
Hi Guys,

@aaronjwhiteside aaronjwhiteside
@staffanselander 
so did anyone ran pullRequest.comment() successfully or not, because I am also facing the issue as mentioned above.
