### ISSUE TITLE
Hitting with following error when more pull requests are working simultaneously 

### ISSUE THREAD

**Issue by nrayapati** [jenkinsci/pipeline-github-plugin#57]
This is on Multi Branch pipeline, and it has credentials configured, works most of the times, but when we have more prs (Like more than 3) running in parallel we hit with this error intermittently. 

I did check on the rate limits there is plenty of it. 

Example Repo: https://github.com/nrayapati/testing-pr

Using the latest version: 2.2.

```groovy
hudson.remoting.ProxyException: org.eclipse.egit.github.core.client.RequestException: You have triggered an abuse detection mechanism. Please wait a few minutes before you try again. (403)
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:585)
	at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:676)
	at org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:795)
	at org.eclipse.egit.github.core.service.CommitService.createStatus(CommitService.java:507)
	at org.jenkinsci.plugins.pipeline.github.PullRequestGroovyObject.createStatus(PullRequestGroovyObject.java:528)
	at org.jenkinsci.plugins.pipeline.github.PullRequestGroovyObject.createStatus(PullRequestGroovyObject.java:508)
	at sun.reflect.GeneratedMethodAccessor375.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:157)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:159)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
```

**Comment by aaronjwhiteside** [comment]
I'm inclined to trust the eclipse GitHub client here, that error is coming directly from GitHub.. I'm not sure what I can do to help solve this issue

**Comment by nrayapati** [comment]
This was an issue with the rate limit.

**Comment by mattnelson** [comment]
I'm seeing this as well. GitHub has a response header that indicates when the request can be retried during abuse detection. Is it desirable to update this plugin to support configuration to opt into these targeted retries?

https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits
