### ISSUE TITLE
review related methods are not working

### ISSUE THREAD

**Issue by jhohertz** [jenkinsci/pipeline-github-plugin#86]
Trying to access any of the review/reviewRequest information consistently results in:

```
ERROR: Stage FAILED: org.eclipse.egit.github.core.client.NoSuchPageException: Parse exception converting JSON to object
```

I'm guessing there was an API change on GitHub's end that needs to be reflected? There is discussion in #45 after it was closed about this.

**Comment by jhohertz** [comment]
Just noting the error is now more detailed. Also, Is this plugin actively maintained?

```
java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:351)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:932)
Caused: com.google.gson.JsonSyntaxException
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at org.eclipse.egit.github.core.client.GitHubClient.parseJson(GitHubClient.java:455)
Caused: java.io.IOException: Parse exception converting JSON to object
	at org.eclipse.egit.github.core.client.GitHubClient.parseJson(GitHubClient.java:457)
	at org.eclipse.egit.github.core.client.GitHubClient.getBody(GitHubClient.java:562)
	at org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:774)
	at org.eclipse.egit.github.core.client.PageIterator.next(PageIterator.java:175)
	at org.eclipse.egit.github.core.client.PageIterator.next(PageIterator.java:1)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:295)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:207)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:162)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:301)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at com.cloudbees.groovy.cps.impl.ForInLoopBlock$ContinuationImpl.increment(ForInLoopBlock.java:61)
	at com.cloudbees.groovy.cps.impl.ForInLoopBlock$ContinuationImpl.loopHead(ForInLoopBlock.java:57)
	at sun.reflect.GeneratedMethodAccessor490.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
```

**Comment by phawzy** [comment]
this isn't fixed yet?
any plans to fix it soon ?
